server:
  port: 8087
  servlet:
    context-path: /chat-service/api

spring:
  application:
    name: chat-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/expense_tracker}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
  expiration: ${JWT_EXPIRATION:86400}  # 24 hours in seconds
  audience: ${JWT_AUDIENCE:31b4428c-275e-11ec-9621-0242ac130002}

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000

logging:
  level:
    com.expense.chat_service: INFO

user:
  service:
    url: ${USER_SERVICE_URL:http://localhost:8019/user-service/api}
expense:
  tracker:
    url: ${EXPENSE_TRACKER_URL:http://localhost:8018/expense-tracker/api}
